import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { BackToTop } from '@/components/layout/BackToTop';

// style imports
import '../assets/styles/index.scss';
import { Footer } from '@/components/layout/Footer';
import { Navbar } from '@/components/layout/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BackToTop />
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
