import type { Metadata } from 'next';
import { BackToTop } from '@/components/layout/BackToTop';

// style imports
import '../assets/styles/index.scss';
import { Footer } from '@/components/layout/Footer';
import { Navbar } from '@/components/layout/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className=''>
        <BackToTop />
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
